### ISSUE TITLE
Door position 

### ISSUE THREAD

**Issue by chr313** [darton/RPiMS#2]
Good afternoon!  First of all, I want to thank you for a wonderful project.  Thank you for your hard work.  The description says: "When any of the doors sensors opens or closed then a message will be sent to the Zabbix server."  Can you please tell me how to implement this in Zabbix server?  with DHT 22 , of course, specified the rpims.dht[2] and rpims.dht[4] keys separately, and it displays temperature and humidity separately in the graphs.  How do you specify doors?  through an agent or a trapper and with what key?  and how to display each door separately, so that when the state of the door open or closed changes, it goes to the server itself?

**Comment by darton** [comment]
You need to import this templates into Zabbix: 
https://github.com/darton/RPiMS/blob/master/templates/rpims_zabbix_host_template.xml
https://github.com/darton/RPiMS/blob/master/templates/rpims_zabbix_template.xml 
In rpims_zabbix_template.xml template, the appropriate zabbix triggers for the temperature, humidity and door sensors are configured.
Door sensor triggering is pre-configured for GPIO_20, GPIO_21 only, if you need more, please do trigger clone.
RPiMS (rpims.py) uses zabbix_sender.sh to activate the appropriate Zabbix triggers.

**Comment by chr313** [comment]
When exporting a template to a host, zabbix stops responding. In my working node, I registered triggers according to your example. There are no errors. But the triggers do not work when the buttons are pressed. Nowhere is it displayed that the button was pressed. Please tell me what could be the reason

**Comment by darton** [comment]
show me the command result (on raspberry pi):

redis-cli get zabbix_agent |awk -F, '{print $4}' |awk -F\" '{print $4}'

and show me the screenshot of the trigger configuration on zabbix

**Comment by chr313** [comment]
Good afternoon!  I'm sorry that.  did not answer for a long time.  Figured out how to do it right.  Thanks again for your hard work and time! Everything works perfectly!
