### ISSUE TITLE
About camera feature.

### ISSUE THREAD

**Issue by hasanaltin** [darton/RPiMS#3]
Have a good day. Thanks for the great project. I realized that there is two problem about camera. One of them is the rotation doesn't work, and the second one is when a door is opened the camera doesn't start recording. Thanks in advance.

**Comment by darton** [comment]
Please do a fresh installation.

**Comment by hasanaltin** [comment]
Thanks for the answer. This morning I made a fresh installation on RP4 and the problem is persisting when i check the http://192.168.xxx.xxx:8080/stream address. On the other hand, I stopped seeing the camera on the frontpage after your new commit. Seems you have some new ideas :)

**Comment by darton** [comment]
download this files:
https://raw.githubusercontent.com/darton/RPiMS/master/RPiMS/videorecorder.sh
https://raw.githubusercontent.com/darton/RPiMS/master/RPiMS/rpims.py
https://raw.githubusercontent.com/darton/RPiMS/master/www/index_html.php

Please, check if you have ffmpeg installed, if not then install:

sudo apt install ffmpeg

and then restart rpims
sudo systemctl restart rpims

**Comment by hasanaltin** [comment]
thanks for the new commit. ffmpeg is checked and seen that was already installed with the fresh installation. the other 3 files were changed and checked with few browsers but the result is still same.

**Comment by darton** [comment]
Show me please:
1.
ls /lib/systemd/system |grep rpims
2.
dpkg -l | grep -Eqw "gdm3|sddm|lxdm|xdm|lightdm|slim|wdm"
3.
cat /etc/os-release 
4.
ls -la /etc/uv4l/
5.
ls -la /home/pi/Videos

**Comment by darton** [comment]
Clear the browser cache.

**Comment by hasanaltin** [comment]
Here is output of the commands as you wish.

![image](https://user-images.githubusercontent.com/62545852/193307013-b51ae10f-5661-40ae-b905-f0440d9f4384.png)

**Comment by darton** [comment]
Please execute the following commands:
sudo mv -f /etc/uv4l/uv4l-raspicam.conf /etc/uv4l/uv4l-raspicam.conf.org
sudo ln -s /var/www/html/conf/uv4l-raspicam.conf /etc/uv4l/uv4l-raspicam.conf

**Comment by darton** [comment]
And now check if the camera parameter control works

**Comment by darton** [comment]
And enable the Legacy Camera support from the Interface Options menu of the following system command and reboot:

    sudo raspi-config
    sudo reboot

**Comment by darton** [comment]
Or use command:
sudo raspi-config nonint do_legacy 0
sudo reboot

**Comment by hasanaltin** [comment]
It started working after moving the conf files to another location. Thanks for your help.

**Comment by darton** [comment]
Thanks for finding the bug. The installer has been improved.
