### ISSUE TITLE
About little changes

### ISSUE THREAD

**Issue by hasanaltin** [darton/RPiMS#4]
Hello Dariusz, I couldn't change the color of the motions. Is there a way to change the color of the text or use a simple picture for different status. For example when the door status is open yellow is okay, but I want to use a simple picture or change the color of the font when the door status ise close. By the way I also discovred a bug which is related to DS18B20 sensor. It doesn't show up at homepage when we enable it.

**Comment by darton** [comment]
It often takes more time before the DS18B20 sensors are detected. Therefore, you currently need to refresh the page manually.

**Comment by darton** [comment]
RPiMS focuses on signaling state changes in Zabbix, so I didn't pay too much attention to the appearance. However, I may make changes here soon.

**Comment by darton** [comment]
From now on, the font color of the status of door sensors and motion sensors depends on their status.

**Comment by hasanaltin** [comment]
Hello Dariusz, thank you for the new implementation. In my opinion it looks better. Thank you so much again.
